bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, X, exec, swaylock -c 282828
bind = $mainMod, D, exec, $menu
bind = $mainMod, W, exec, firefox
bind = $mainMod, P, exec, firefox --private-window
bind = $mainMod, F4, exec, ~/.local/bin/powermenu.sh
bind = $mainMod SHIFT, code:21, exec, ~/.local/bin/zoom/zoom.sh in
bind = $mainMod SHIFT, code:20, exec, ~/.local/bin/zoom/zoom.sh out
bind = $mainMod SHIFT, code:22, exec, ~/.local/bin/zoom/zoom.sh reset
bind = $mainMod, code:107, exec, grim -t jpeg ~/pictures/screenshots/$(date +%Y-%m-%d_%H-%m-%s).jpg
bind = , code:107, exec, grim -t jpeg -g "$(slurp)" ~/pictures/screenshots/$(date +%Y-%m-%d_%H-%m-%s).jpg
